### ISSUE TITLE
In password.js

### ISSUE THREAD

**Issue by samhstn** [javascriptthehut/someprojectwithminimalfrontend#19]
It's cool that you are trying to make a encryption function, but why reinvent what node already has native to it.
Check out this for an example of using the native node crypto module
https://github.com/chris-rock/node-crypto-examples/blob/master/crypto-gcm.js
Best of all you should use actual encryption libraries such as bcrypt

**Comment by nogainbar** [comment]
hey sam!

we didnt ended up using that module in the end(password.js), just forgot to delete it.. 
in fact we realized that it would be a crazy task to go with that. we used uuid module to create a token instead and save it on server memory.

will delete the file now! :)
thanx! 👍

**Comment by samhstn** [comment]
Nice, good you didn't pursue building this, there are prebuilt things you can use instead
